# Generated by Django 4.0.5 on 2023-07-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'usuario_con_permiso_de_visualizacion'),)},
        ),
    ]
