# Generated by Django 4.0.5 on 2023-07-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='VehiculoModel',
        ),
    ]
